---
title: "Basic_EDA"
author: "Aleksei Zverev"
date: "2023-06-02"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=TRUE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(fig.width = 10, fig.height = 6)
 

library('phyloseq')
library('tidyverse')



set.seed(5678)
setwd('~/Praktikum/TyumGU_2023/')
ps <- readRDS("ps.RData")
ps
```

## Brief view on samples

```{r}
sample_sums(ps) %>% sort()
taxa_sums(ps) %>%  hist()
```




## Remove chloroplast and mitochondria

```{r}
# ps@tax_table %>% View()

ps.filtered <- subset_taxa(ps, Phylum != "NA")

asvs.keep <-ps@tax_table %>% 
      data.frame() %>%  
      filter((Family != "Mitochondria" & Order != "Chloroplast") %>%
              replace_na(TRUE)) %>% 
      rownames()
ps.notrash <- prune_taxa(asvs.keep, ps.filtered)

# ps.notrash@tax_table %>% View()

saveRDS(ps.notrash, "ps.no.organells.RData")
```


## Plot barplots

```{r}
bargraph <- function(ps, rank, threshold=0.05, percents=FALSE){
  require(dplyr)
  require(ggplot2)
  require(phyloseq)
  
  ps <- prune_taxa(taxa_sums(ps) > 0, ps)
  ps2 <- tax_glom(ps, taxrank = rank)
  ps3 = transform_sample_counts(ps2, function(x) x / sum(x) )
  data <- psmelt(ps3) # create dataframe from phyloseq object
  data$Plot <- as.character(data[,rank]) # convert to character
  data$Plot[data$Abundance < threshold] <- paste0("<", threshold, " abund.")
  medians <- data %>% group_by(Plot) %>% mutate(median=median(data$Abundance))
  remainder <- medians[medians$median <= threshold,]$Plot
  data$Percentage = ifelse(data$Plot != paste0("<", threshold, " abund."),
                           round(data$Abundance, 3)*100, NA)
  
  # create palette long enough for our data
  base.palette <- c("darkblue", "darkgoldenrod1", "darkseagreen", "darkorchid", "darkolivegreen1", "lightskyblue", 
                    "darkgreen", "deeppink", "khaki2", "firebrick", "brown1", "darkorange1", "cyan1", "royalblue4", 
                    "darksalmon", "dodgerblue3", "steelblue1", "darkgoldenrod1", "brown1", "cyan1", "darkgrey")
  required.colors <- nlevels(factor(data$Plot))
  repeats = required.colors %/% length(base.palette) + 1
  palette <- rep(base.palette, length.out = repeats * length(base.palette))
  
  p <- ggplot(data=data, aes(x=Sample, y=Abundance, fill=Plot))
  p + geom_bar(aes(), stat="identity", position="stack") + theme_light() +
    scale_fill_manual(values = palette) +
    theme(legend.position="bottom") + guides() +
    theme(axis.text.x = element_text(angle = 90)) +
    if (percents) {
      geom_text(aes(label = Percentage),
                position = position_stack(vjust = 0.5), size = 1.5)
    }
  
}

bargraph(ps.notrash, "Phylum", 0.02) +
  facet_grid(~MainPlant + Soil ,scales = 'free_x') +
  theme(axis.text.x = element_blank())
```

## Plot alpha-diversity

```{r}
sample_sums(ps.notrash) %>% sort()

ps.raref <- rarefy_even_depth(ps.notrash, sample.size = 8000)

plot_richness(ps.raref, x = "MainPlant", measures=c("Observed", "Shannon"), color = "Soil")
```

## Beta-diversity

```{r}
ordinations <- ordinate(ps.notrash, "NMDS", "bray")
plot_ordination(ps.notrash, ordinations, type="taxa", color="Phylum")

plot_ordination(ps.notrash, ordinations, type="samples", color="MainPlant", shape = "Soil")
```

## Ideas to check

1. 
2.
3.